from django.db import migrations, models
import django.db.models.deletion
import django.conf

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='School',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=255,unique=True)),('district',models.CharField(blank=True,max_length=100)),('country',models.CharField(default='Rwanda',max_length=50)),('active',models.BooleanField(default=True))]),
      migrations.CreateModel(name='BookCatalog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(max_length=100,unique=True)),('title',models.CharField(max_length=255)),('author',models.CharField(blank=True,max_length=255)),('grade',models.CharField(blank=True,max_length=100)),('category',models.CharField(blank=True,max_length=100)),('isbn',models.CharField(blank=True,max_length=50)),('publisher',models.CharField(blank=True,max_length=255)),('language',models.CharField(blank=True,max_length=80))]),
      migrations.CreateModel(name='Librarian',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('phone',models.CharField(blank=True,max_length=30)),('verified',models.BooleanField(default=True)),('school',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='librarians',to='books.school')),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='librarian_profile',to=django.conf.settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='BookScan',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('code',models.CharField(db_index=True,max_length=100)),('title',models.CharField(blank=True,max_length=255)),('author',models.CharField(blank=True,max_length=255)),('grade',models.CharField(blank=True,max_length=100)),('category',models.CharField(blank=True,max_length=100)),('isbn',models.CharField(blank=True,max_length=50)),('publisher',models.CharField(blank=True,max_length=255)),('language',models.CharField(blank=True,max_length=80)),('cover',models.ImageField(blank=True,null=True,upload_to='covers/%Y/%m/%d/')),('matched_catalog',models.BooleanField(default=False)),('scanned_at',models.DateTimeField(auto_now_add=True,db_index=True)),('librarian',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='scans',to='books.librarian')),('school',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='scans',to='books.school'))]),
    ]
